In [1]:
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
import warnings
warnings.filterwarnings('ignore')

In [2]:
df_organizations = pd.read_csv('organizations.csv')
df_investments = pd.read_csv('investments.csv')
df_funding_rounds = pd.read_csv('funding_rounds.csv')
df_investors = pd.read_csv('investors.csv', low_memory=False)

In [3]:
df_invetment_investor = pd.merge(df_investments, df_investors, how='left', left_on='investor_uuid', right_on='uuid')
df_invetment_investor.columns

Index(['uuid_x', 'name_x', 'type_x', 'permalink_x', 'cb_url_x', 'rank_x',
       'created_at_x', 'updated_at_x', 'funding_round_uuid',
       'funding_round_name', 'investor_uuid', 'investor_name', 'investor_type',
       'is_lead_investor', 'uuid_y', 'name_y', 'type_y', 'permalink_y',
       'cb_url_y', 'rank_y', 'created_at_y', 'updated_at_y', 'roles', 'domain',
       'country_code', 'state_code', 'region', 'city', 'investor_types',
       'investment_count', 'total_funding_usd', 'total_funding',
       'total_funding_currency_code', 'founded_on', 'closed_on',
       'facebook_url', 'linkedin_url', 'twitter_url', 'logo_url'],
      dtype='object')

In [4]:
df_invetment_investor['name_y'].isna().sum()

2

In [5]:
df_invetment_investor_fr = pd.merge(df_invetment_investor, df_funding_rounds, how='left', left_on='funding_round_uuid', right_on='uuid')
df_invetment_investor_fr

,uuid_x,name_x,type_x,permalink_x,cb_url_x,rank_x,created_at_x,updated_at_x,funding_round_uuid,funding_round_name,...,raised_amount_usd,raised_amount,raised_amount_currency_code,post_money_valuation_usd,post_money_valuation,post_money_valuation_currency_code,investor_count,org_uuid,org_name,lead_investor_uuids
0,524986f0-3049-54a4-fa72-f60897a5e61d,Accel investment in Series A - Facebook,investment,accel-partners-invested-in-facebook-series-a--...,https://www.crunchbase.com/investment/accel-pa...,NaN,2007-05-27 06:09:10,2018-02-13 00:52:57,d950d7a5-79ff-fb93-ca87-13386b0e2feb,Series A - Facebook,...,12700000.0,12700000.0,USD,98000000.0,98000000.0,USD,5.0,df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,b08efc27-da40-505a-6f9d-c9e14247bf36
1,6556ab92-6465-25aa-1ffc-7f8b4b09a476,Greylock Partners investment in Series B - Fac...,investment,greylock-invested-in-facebook-series-b--6fae39...,https://www.crunchbase.com/investment/greylock...,NaN,2007-05-27 06:09:36,2018-02-13 00:53:20,6fae3958-a001-27c0-fb7e-666266aedd78,Series B - Facebook,...,27500000.0,27500000.0,USD,502500000.0,502500000.0,USD,5.0,df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,"e2006571-6b7a-e477-002a-f7014f48a7e3,8d5c7e48-..."
2,0216e06a-61f8-9cf1-19ba-20811229c53e,Meritech Capital Partners investment in Series...,investment,meritech-capital-partners-invested-in-facebook...,https://www.crunchbase.com/investment/meritech...,NaN,2007-05-27 06:09:36,2019-03-27 19:50:32,6fae3958-a001-27c0-fb7e-666266aedd78,Series B - Facebook,...,27500000.0,27500000.0,USD,502500000.0,502500000.0,USD,5.0,df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,"e2006571-6b7a-e477-002a-f7014f48a7e3,8d5c7e48-..."
3,dadd7d86-520d-5e35-3033-fc1d8792ab91,Trinity Ventures investment in Series B - Phot...,investment,trinity-ventures-invested-in-photobucket-serie...,https://www.crunchbase.com/investment/trinity-...,NaN,2007-05-29 11:05:59,2018-02-13 00:55:58,bcd5a63d-ed99-6963-0dd2-e36f6582f846,Series B - Photobucket,...,10500000.0,10500000.0,USD,NaN,NaN,USD,2.0,f53cb4de-236e-0b1b-dee8-7104a8b018f9,Photobucket,NaN
4,581c4b38-9653-7117-9bd4-7ffe5c7eba69,Founders Fund investment in Series A - Geni,investment,founders-fund-invested-in-geni-series-a--60e6a...,https://www.crunchbase.com/investment/founders...,NaN,2007-05-31 20:19:28,2018-02-13 00:53:04,60e6afd9-1215-465a-dd17-0ed600d4e29b,Series A - Geni,...,NaN,NaN,NaN,10000000.0,10000000.0,USD,1.0,4111dc8b-c0df-2d24-ed33-30cd137b3098,Geni,fb2f8884-ec07-895a-48d7-d9a9d4d7175c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448472,19c44464-1ab1-4fac-9508-8798d8f6db04,SOSV investment in Convertible Note - Planetar...,investment,sosv-invested-in-planetarians-convertible-note...,https://www.crunchbase.com/investment/sosv-inv...,NaN,2020-01-07 23:35:04,2020-01-07 23:35:04,e593cebf-be51-4cf6-bb5a-f0b18a6b04c4,Convertible Note - Planetarians,...,NaN,NaN,NaN,NaN,NaN,USD,2.0,bf6d3b88-e5c3-b3b3-7931-f9bb3eb06bb5,Planetarians,NaN
448473,ce137325-4f4d-45e2-b285-d47ef00cb9de,MOX investment in Seed Round - PODD,investment,mox-3-invested-in-podd-seed--ef35301b--ce137325,https://www.crunchbase.com/investment/mox-3-in...,NaN,2020-01-07 23:36:42,2020-01-07 23:36:42,ef35301b-45d4-46e6-881a-f9d186e79922,Seed Round - PODD,...,NaN,NaN,NaN,NaN,NaN,USD,2.0,3545c952-22d2-7e1a-5bee-339525742fe3,PODD,NaN
448474,061b7643-2f27-4811-9dc1-28a7875a4975,SOSV investment in Seed Round - PODD,investment,sosv-invested-in-podd-seed--ef35301b--061b7643,https://www.crunchbase.com/investment/sosv-inv...,NaN,2020-01-07 23:36:42,2020-01-07 23:36:42,ef35301b-45d4-46e6-881a-f9d186e79922,Seed Round - PODD,...,NaN,NaN,NaN,NaN,NaN,USD,2.0,3545c952-22d2-7e1a-5bee-339525742fe3,PODD,NaN
448475,5b50e36f-f9eb-4a12-99c6-55c24b9e828b,SOSV investment in Seed Round - Quidli,investment,sosv-invested-in-quidli-seed--d486cc0e--5b50e36f,https://www.crunchbase.com/investment/sosv-inv...,NaN,2020-01-07 23:42:32,2020-01-07 23:42:32,d486cc0e-20a9-4e1b-a3e2-a509137369a1,Seed Round - Quidli,...,NaN,NaN,NaN,NaN,NaN,USD,2.0,03093a7f-4478-4e64-a541-fc1d54014d26,Quidli,NaN
448476,098b4ea8-1753-4f22-9a36-0e1ad7207159,dlab investment in Seed Round - Quidli,investment,dlabvc-invested-in-quidli-seed--d486cc0e--098b...,https://www.crunchbase.com/investment/dlabvc-i...,NaN,2020-01-07 23:42:32,2020-01-07 23:42:32,d486cc0e-20a9-4e1b-a3e2-a509137369a1,Seed Round - Quidli,...,NaN,NaN,NaN,NaN,NaN,USD,2.0,03093a7f-4478-4e64-a541-fc1d54014d26,Quidli,NaN

In [6]:
df_invetment_investor_fr.columns

Index(['uuid_x', 'name_x', 'type_x', 'permalink_x', 'cb_url_x', 'rank_x',
       'created_at_x', 'updated_at_x', 'funding_round_uuid',
       'funding_round_name', 'investor_uuid', 'investor_name', 'investor_type',
       'is_lead_investor', 'uuid_y', 'name_y', 'type_y', 'permalink_y',
       'cb_url_y', 'rank_y', 'created_at_y', 'updated_at_y', 'roles', 'domain',
       'country_code_x', 'state_code_x', 'region_x', 'city_x',
       'investor_types', 'investment_count', 'total_funding_usd',
       'total_funding', 'total_funding_currency_code', 'founded_on',
       'closed_on', 'facebook_url', 'linkedin_url', 'twitter_url', 'logo_url',
       'uuid', 'name', 'type', 'permalink', 'cb_url', 'rank', 'created_at',
       'updated_at', 'country_code_y', 'state_code_y', 'region_y', 'city_y',
       'investment_type', 'announced_on', 'raised_amount_usd', 'raised_amount',
       'raised_amount_currency_code', 'post_money_valuation_usd',
       'post_money_valuation', 'post_money_valuation_currency_code',
       'investor_count', 'org_uuid', 'org_name', 'lead_investor_uuids'],
      dtype='object')

In [7]:
df_iif = df_invetment_investor_fr[['uuid_x', 'funding_round_uuid','investor_uuid','investor_name','investor_type','is_lead_investor','roles','country_code_x','region_x','city_x','investor_types','investment_count','total_funding','founded_on','closed_on','country_code_y','state_code_y','region_y','city_y','investment_type','announced_on','raised_amount','post_money_valuation','investor_count','org_uuid','org_name','lead_investor_uuids']]
df_iif

,uuid_x,funding_round_uuid,investor_uuid,investor_name,investor_type,is_lead_investor,roles,country_code_x,region_x,city_x,...,region_y,city_y,investment_type,announced_on,raised_amount,post_money_valuation,investor_count,org_uuid,org_name,lead_investor_uuids
0,524986f0-3049-54a4-fa72-f60897a5e61d,d950d7a5-79ff-fb93-ca87-13386b0e2feb,b08efc27-da40-505a-6f9d-c9e14247bf36,Accel,organization,True,"company,investor",USA,California,Palo Alto,...,California,Menlo Park,series_a,2005-05-01,12700000.0,98000000.0,5.0,df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,b08efc27-da40-505a-6f9d-c9e14247bf36
1,6556ab92-6465-25aa-1ffc-7f8b4b09a476,6fae3958-a001-27c0-fb7e-666266aedd78,e2006571-6b7a-e477-002a-f7014f48a7e3,Greylock Partners,organization,True,investor,USA,California,Menlo Park,...,California,Menlo Park,series_b,2006-04-01,27500000.0,502500000.0,5.0,df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,"e2006571-6b7a-e477-002a-f7014f48a7e3,8d5c7e48-..."
2,0216e06a-61f8-9cf1-19ba-20811229c53e,6fae3958-a001-27c0-fb7e-666266aedd78,8d5c7e48-82da-3025-dd46-346a31bab86f,Meritech Capital Partners,organization,True,investor,USA,California,Palo Alto,...,California,Menlo Park,series_b,2006-04-01,27500000.0,502500000.0,5.0,df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,"e2006571-6b7a-e477-002a-f7014f48a7e3,8d5c7e48-..."
3,dadd7d86-520d-5e35-3033-fc1d8792ab91,bcd5a63d-ed99-6963-0dd2-e36f6582f846,7ca12f7a-2f8e-48b4-a8d1-1a33a0e275b9,Trinity Ventures,organization,NaN,investor,USA,California,Menlo Park,...,Colorado,Denver,series_b,2006-05-01,10500000.0,NaN,2.0,f53cb4de-236e-0b1b-dee8-7104a8b018f9,Photobucket,NaN
4,581c4b38-9653-7117-9bd4-7ffe5c7eba69,60e6afd9-1215-465a-dd17-0ed600d4e29b,fb2f8884-ec07-895a-48d7-d9a9d4d7175c,Founders Fund,organization,True,investor,USA,California,San Francisco,...,California,West Hollywood,series_a,2007-01-17,NaN,10000000.0,1.0,4111dc8b-c0df-2d24-ed33-30cd137b3098,Geni,fb2f8884-ec07-895a-48d7-d9a9d4d7175c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448472,19c44464-1ab1-4fac-9508-8798d8f6db04,e593cebf-be51-4cf6-bb5a-f0b18a6b04c4,39041e62-6b24-ae8d-1347-4cea947e832c,SOSV,organization,NaN,investor,USA,New Jersey,Princeton,...,California,Palo Alto,convertible_note,2019-12-17,NaN,NaN,2.0,bf6d3b88-e5c3-b3b3-7931-f9bb3eb06bb5,Planetarians,NaN
448473,ce137325-4f4d-45e2-b285-d47ef00cb9de,ef35301b-45d4-46e6-881a-f9d186e79922,523023cb-a5bc-c4ff-a7dd-d6d63afb983c,MOX,organization,NaN,investor,TWN,T'ai-pei,Taipei,...,NaN,NaN,seed,2019-10-24,NaN,NaN,2.0,3545c952-22d2-7e1a-5bee-339525742fe3,PODD,NaN
448474,061b7643-2f27-4811-9dc1-28a7875a4975,ef35301b-45d4-46e6-881a-f9d186e79922,39041e62-6b24-ae8d-1347-4cea947e832c,SOSV,organization,NaN,investor,USA,New Jersey,Princeton,...,NaN,NaN,seed,2019-10-24,NaN,NaN,2.0,3545c952-22d2-7e1a-5bee-339525742fe3,PODD,NaN
448475,5b50e36f-f9eb-4a12-99c6-55c24b9e828b,d486cc0e-20a9-4e1b-a3e2-a509137369a1,39041e62-6b24-ae8d-1347-4cea947e832c,SOSV,organization,NaN,investor,USA,New Jersey,Princeton,...,Ile-de-France,Paris,seed,2019-11-13,NaN,NaN,2.0,03093a7f-4478-4e64-a541-fc1d54014d26,Quidli,NaN
448476,098b4ea8-1753-4f22-9a36-0e1ad7207159,d486cc0e-20a9-4e1b-a3e2-a509137369a1,7195d499-3878-423e-99d9-b4f9207d2cbc,dlab,organization,NaN,investor,USA,New York,New York,...,Ile-de-France,Paris,seed,2019-11-13,NaN,NaN,2.0,03093a7f-4478-4e64-a541-fc1d54014d26,Quidli,NaN

In [8]:
df_iif.rename(columns={"uuid_x":"investment_uuid"}, inplace = True)
df_iif.rename(columns={"roles":"investor_roles"}, inplace = True)
df_iif.rename(columns={"investment_type":"Investment_round"}, inplace = True)

df_iif.rename(columns={"investor_types":"vc_types"}, inplace = True)
df_iif.rename(columns={"country_code_x":"Investor_country_code"}, inplace = True)

df_iif.rename(columns={"region_x":"investor_region"}, inplace = True)

df_iif.rename(columns={"city_x":"investor_city"}, inplace = True)

df_iif.rename(columns={"investor_types":"vc_types"}, inplace = True)
df_iif.rename(columns={"country_code_y":"org_country_code"}, inplace = True)

# df_iif.rename(columns={"state_code_y":"org_state_code"}, inplace = True)

df_iif.rename(columns={"region_y":"org_region"}, inplace = True)

df_iif.rename(columns={"city_y":"org_city"}, inplace = True)

df_iif

,investment_uuid,funding_round_uuid,investor_uuid,investor_name,investor_type,is_lead_investor,investor_roles,Investor_country_code,investor_region,investor_city,...,org_region,org_city,Investment_round,announced_on,raised_amount,post_money_valuation,investor_count,org_uuid,org_name,lead_investor_uuids
0,524986f0-3049-54a4-fa72-f60897a5e61d,d950d7a5-79ff-fb93-ca87-13386b0e2feb,b08efc27-da40-505a-6f9d-c9e14247bf36,Accel,organization,True,"company,investor",USA,California,Palo Alto,...,California,Menlo Park,series_a,2005-05-01,12700000.0,98000000.0,5.0,df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,b08efc27-da40-505a-6f9d-c9e14247bf36
1,6556ab92-6465-25aa-1ffc-7f8b4b09a476,6fae3958-a001-27c0-fb7e-666266aedd78,e2006571-6b7a-e477-002a-f7014f48a7e3,Greylock Partners,organization,True,investor,USA,California,Menlo Park,...,California,Menlo Park,series_b,2006-04-01,27500000.0,502500000.0,5.0,df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,"e2006571-6b7a-e477-002a-f7014f48a7e3,8d5c7e48-..."
2,0216e06a-61f8-9cf1-19ba-20811229c53e,6fae3958-a001-27c0-fb7e-666266aedd78,8d5c7e48-82da-3025-dd46-346a31bab86f,Meritech Capital Partners,organization,True,investor,USA,California,Palo Alto,...,California,Menlo Park,series_b,2006-04-01,27500000.0,502500000.0,5.0,df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,"e2006571-6b7a-e477-002a-f7014f48a7e3,8d5c7e48-..."
3,dadd7d86-520d-5e35-3033-fc1d8792ab91,bcd5a63d-ed99-6963-0dd2-e36f6582f846,7ca12f7a-2f8e-48b4-a8d1-1a33a0e275b9,Trinity Ventures,organization,NaN,investor,USA,California,Menlo Park,...,Colorado,Denver,series_b,2006-05-01,10500000.0,NaN,2.0,f53cb4de-236e-0b1b-dee8-7104a8b018f9,Photobucket,NaN
4,581c4b38-9653-7117-9bd4-7ffe5c7eba69,60e6afd9-1215-465a-dd17-0ed600d4e29b,fb2f8884-ec07-895a-48d7-d9a9d4d7175c,Founders Fund,organization,True,investor,USA,California,San Francisco,...,California,West Hollywood,series_a,2007-01-17,NaN,10000000.0,1.0,4111dc8b-c0df-2d24-ed33-30cd137b3098,Geni,fb2f8884-ec07-895a-48d7-d9a9d4d7175c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448472,19c44464-1ab1-4fac-9508-8798d8f6db04,e593cebf-be51-4cf6-bb5a-f0b18a6b04c4,39041e62-6b24-ae8d-1347-4cea947e832c,SOSV,organization,NaN,investor,USA,New Jersey,Princeton,...,California,Palo Alto,convertible_note,2019-12-17,NaN,NaN,2.0,bf6d3b88-e5c3-b3b3-7931-f9bb3eb06bb5,Planetarians,NaN
448473,ce137325-4f4d-45e2-b285-d47ef00cb9de,ef35301b-45d4-46e6-881a-f9d186e79922,523023cb-a5bc-c4ff-a7dd-d6d63afb983c,MOX,organization,NaN,investor,TWN,T'ai-pei,Taipei,...,NaN,NaN,seed,2019-10-24,NaN,NaN,2.0,3545c952-22d2-7e1a-5bee-339525742fe3,PODD,NaN
448474,061b7643-2f27-4811-9dc1-28a7875a4975,ef35301b-45d4-46e6-881a-f9d186e79922,39041e62-6b24-ae8d-1347-4cea947e832c,SOSV,organization,NaN,investor,USA,New Jersey,Princeton,...,NaN,NaN,seed,2019-10-24,NaN,NaN,2.0,3545c952-22d2-7e1a-5bee-339525742fe3,PODD,NaN
448475,5b50e36f-f9eb-4a12-99c6-55c24b9e828b,d486cc0e-20a9-4e1b-a3e2-a509137369a1,39041e62-6b24-ae8d-1347-4cea947e832c,SOSV,organization,NaN,investor,USA,New Jersey,Princeton,...,Ile-de-France,Paris,seed,2019-11-13,NaN,NaN,2.0,03093a7f-4478-4e64-a541-fc1d54014d26,Quidli,NaN
448476,098b4ea8-1753-4f22-9a36-0e1ad7207159,d486cc0e-20a9-4e1b-a3e2-a509137369a1,7195d499-3878-423e-99d9-b4f9207d2cbc,dlab,organization,NaN,investor,USA,New York,New York,...,Ile-de-France,Paris,seed,2019-11-13,NaN,NaN,2.0,03093a7f-4478-4e64-a541-fc1d54014d26,Quidli,NaN

In [9]:
df_iif[['investor_uuid','is_lead_investor', 'lead_investor_uuids']]

,investor_uuid,is_lead_investor,lead_investor_uuids
0,b08efc27-da40-505a-6f9d-c9e14247bf36,True,b08efc27-da40-505a-6f9d-c9e14247bf36
1,e2006571-6b7a-e477-002a-f7014f48a7e3,True,"e2006571-6b7a-e477-002a-f7014f48a7e3,8d5c7e48-..."
2,8d5c7e48-82da-3025-dd46-346a31bab86f,True,"e2006571-6b7a-e477-002a-f7014f48a7e3,8d5c7e48-..."
3,7ca12f7a-2f8e-48b4-a8d1-1a33a0e275b9,NaN,NaN
4,fb2f8884-ec07-895a-48d7-d9a9d4d7175c,True,fb2f8884-ec07-895a-48d7-d9a9d4d7175c
...,...,...,...
448472,39041e62-6b24-ae8d-1347-4cea947e832c,NaN,NaN
448473,523023cb-a5bc-c4ff-a7dd-d6d63afb983c,NaN,NaN
448474,39041e62-6b24-ae8d-1347-4cea947e832c,NaN,NaN
448475,39041e62-6b24-ae8d-1347-4cea947e832c,NaN,NaN
448476,7195d499-3878-423e-99d9-b4f9207d2cbc,NaN,NaN

In [10]:
df_iif['lead_investor_uuids'].fillna('none', inplace = True)
# lst = df_iif['lead_investor_uuids'].apply(lambda x: str(x.split(','))).to_numpy()
# np.unique(lst)

In [11]:
# Determine the maximum number of comma-separated values
max_values = df_iif['lead_investor_uuids'].str.split(',').apply(len).max()

# Generate new column names
new_column_names = ['lead_investor_{}'.format(i) for i in range(1, max_values+1)]

# Split the column
df_iif[new_column_names] = df_iif['lead_investor_uuids'].str.split(',', expand=True)

In [12]:
df_iif['lead_investor_available'] = False  # Initialize column with False
df_iif.loc[df_iif['lead_investor_uuids'] != 'none', 'lead_investor_available'] = True  # Set to True where condition is met

In [13]:
# df_iif.to_csv('df_iif.csv')
df_iif.columns

Index(['investment_uuid', 'funding_round_uuid', 'investor_uuid',
       'investor_name', 'investor_type', 'is_lead_investor', 'investor_roles',
       'Investor_country_code', 'investor_region', 'investor_city', 'vc_types',
       'investment_count', 'total_funding', 'founded_on', 'closed_on',
       'org_country_code', 'state_code_y', 'org_region', 'org_city',
       'Investment_round', 'announced_on', 'raised_amount',
       'post_money_valuation', 'investor_count', 'org_uuid', 'org_name',
       'lead_investor_uuids', 'lead_investor_1', 'lead_investor_2',
       'lead_investor_3', 'lead_investor_4', 'lead_investor_5',
       'lead_investor_6', 'lead_investor_7', 'lead_investor_8',
       'lead_investor_9', 'lead_investor_available'],
      dtype='object')

In [14]:
df_organizations.columns

Index(['uuid', 'name', 'type', 'permalink', 'cb_url', 'rank', 'created_at',
       'updated_at', 'legal_name', 'roles', 'domain', 'homepage_url',
       'country_code', 'state_code', 'region', 'city', 'address',
       'postal_code', 'status', 'short_description', 'category_list',
       'category_groups_list', 'num_funding_rounds', 'total_funding_usd',
       'total_funding', 'total_funding_currency_code', 'founded_on',
       'last_funding_on', 'closed_on', 'employee_count', 'email', 'phone',
       'facebook_url', 'linkedin_url', 'twitter_url', 'logo_url', 'alias1',
       'alias2', 'alias3', 'primary_role', 'num_exits'],
      dtype='object')

In [15]:
df_org_new = df_organizations[['uuid', 'roles', 'country_code', 'region', 'city', 'address','postal_code', 'status', 'category_list', 'category_groups_list', 'num_funding_rounds', 'total_funding_usd', 'founded_on','last_funding_on', 'closed_on', 'employee_count', 'alias1',
       'alias2', 'alias3', 'primary_role', 'num_exits']]

# 'total_funding_y','total_funding_currency_code'

In [16]:
df_iifo = pd.merge(df_iif, df_org_new, how='left', left_on='org_uuid', right_on='uuid')
df_iifo

,investment_uuid,funding_round_uuid,investor_uuid,investor_name,investor_type,is_lead_investor,investor_roles,Investor_country_code,investor_region,investor_city,...,total_funding_usd,founded_on_y,last_funding_on,closed_on_y,employee_count,alias1,alias2,alias3,primary_role,num_exits
0,524986f0-3049-54a4-fa72-f60897a5e61d,d950d7a5-79ff-fb93-ca87-13386b0e2feb,b08efc27-da40-505a-6f9d-c9e14247bf36,Accel,organization,True,"company,investor",USA,California,Palo Alto,...,2.335700e+09,2004-02-04,2012-03-10,NaN,10000+,NaN,NaN,NaN,company,NaN
1,6556ab92-6465-25aa-1ffc-7f8b4b09a476,6fae3958-a001-27c0-fb7e-666266aedd78,e2006571-6b7a-e477-002a-f7014f48a7e3,Greylock Partners,organization,True,investor,USA,California,Menlo Park,...,2.335700e+09,2004-02-04,2012-03-10,NaN,10000+,NaN,NaN,NaN,company,NaN
2,0216e06a-61f8-9cf1-19ba-20811229c53e,6fae3958-a001-27c0-fb7e-666266aedd78,8d5c7e48-82da-3025-dd46-346a31bab86f,Meritech Capital Partners,organization,True,investor,USA,California,Palo Alto,...,2.335700e+09,2004-02-04,2012-03-10,NaN,10000+,NaN,NaN,NaN,company,NaN
3,dadd7d86-520d-5e35-3033-fc1d8792ab91,bcd5a63d-ed99-6963-0dd2-e36f6582f846,7ca12f7a-2f8e-48b4-a8d1-1a33a0e275b9,Trinity Ventures,organization,NaN,investor,USA,California,Menlo Park,...,4.343413e+07,2003-06-01,2016-08-08,NaN,101-250,Ontela,Photobucket,NaN,company,1.0
4,581c4b38-9653-7117-9bd4-7ffe5c7eba69,60e6afd9-1215-465a-dd17-0ed600d4e29b,fb2f8884-ec07-895a-48d7-d9a9d4d7175c,Founders Fund,organization,True,investor,USA,California,San Francisco,...,1.500000e+07,2006-06-01,2009-01-19,NaN,11-50,NaN,NaN,NaN,company,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448472,19c44464-1ab1-4fac-9508-8798d8f6db04,e593cebf-be51-4cf6-bb5a-f0b18a6b04c4,39041e62-6b24-ae8d-1347-4cea947e832c,SOSV,organization,NaN,investor,USA,New Jersey,Princeton,...,7.500000e+05,2017-01-01,2019-12-17,NaN,1-10,NaN,NaN,NaN,company,NaN
448473,ce137325-4f4d-45e2-b285-d47ef00cb9de,ef35301b-45d4-46e6-881a-f9d186e79922,523023cb-a5bc-c4ff-a7dd-d6d63afb983c,MOX,organization,NaN,investor,TWN,T'ai-pei,Taipei,...,NaN,2004-05-01,2019-10-24,NaN,11-50,NaN,NaN,NaN,company,NaN
448474,061b7643-2f27-4811-9dc1-28a7875a4975,ef35301b-45d4-46e6-881a-f9d186e79922,39041e62-6b24-ae8d-1347-4cea947e832c,SOSV,organization,NaN,investor,USA,New Jersey,Princeton,...,NaN,2004-05-01,2019-10-24,NaN,11-50,NaN,NaN,NaN,company,NaN
448475,5b50e36f-f9eb-4a12-99c6-55c24b9e828b,d486cc0e-20a9-4e1b-a3e2-a509137369a1,39041e62-6b24-ae8d-1347-4cea947e832c,SOSV,organization,NaN,investor,USA,New Jersey,Princeton,...,NaN,2018-02-01,2019-11-13,NaN,1-10,NaN,NaN,NaN,company,NaN
448476,098b4ea8-1753-4f22-9a36-0e1ad7207159,d486cc0e-20a9-4e1b-a3e2-a509137369a1,7195d499-3878-423e-99d9-b4f9207d2cbc,dlab,organization,NaN,investor,USA,New York,New York,...,NaN,2018-02-01,2019-11-13,NaN,1-10,NaN,NaN,NaN,company,NaN

In [18]:
df_iifo.to_csv('investor_startup.csv')

In [20]:
df_iifo = df_iifo[['investor_uuid','investor_name','org_uuid','org_name','raised_amount','Investment_round']]

In [21]:
df_iifo.to_csv('investor_startup_rel.csv')

In [22]:
df_iifo = df_iifo.groupby(['org_uuid', 'org_name', 'investor_uuid', 'investor_name']).size().reset_index(name='frequency')

df_iifo

,org_uuid,org_name,investor_uuid,investor_name,frequency
0,00000aa4-ba42-9b68-a9c3-040c9f3bf9b9,Formel D GmbH,5155fe13-45ed-d756-22a0-4b2b00633f1a,CITIC Capital Holdings,1
1,000014da-0c46-b9cb-0941-3a93c027b119,Resilio,07d82047-c9b7-1328-137f-117dacaa50ef,Vaekstfonden - The Danish Growth Fund,1
2,000014da-0c46-b9cb-0941-3a93c027b119,Resilio,0f704b0c-5a9f-d48a-6ff8-e7f15ab5873c,The Market Development Fund,1
3,000014da-0c46-b9cb-0941-3a93c027b119,Resilio,2e96c6d3-92b8-4d14-a4d8-c7613f0e2115,D.BOYTER,1
4,000014da-0c46-b9cb-0941-3a93c027b119,Resilio,4b438a93-38f0-26db-b635-44c9402a60ff,SYBO Games,1
...,...,...,...,...,...
354643,ffffabce-6d4a-b3d1-13c0-4e90cedf5270,ERNIT,bfbebfed-8022-f233-07cd-6974a3458a02,Global FinTech Hackcelerator,1
354644,ffffabce-6d4a-b3d1-13c0-4e90cedf5270,ERNIT,cee27959-9190-3859-5ad0-f8339e49cccf,Seed Capital,1
354645,ffffabce-6d4a-b3d1-13c0-4e90cedf5270,ERNIT,d9369c07-9a13-6d6a-f839-ad668b98ca31,Spar Nord Bank A/S,1
354646,ffffabce-6d4a-b3d1-13c0-4e90cedf5270,ERNIT,e16a53e2-8d11-149f-6ca1-625c8f527914,Tommy Korsholt,1
354647,ffffabce-6d4a-b3d1-13c0-4e90cedf5270,ERNIT,e6da716e-5b47-4a2a-cb02-f685ab23f46d,Innovation Fund Denmark,1

In [23]:
df_iifo.to_csv('investor_startup_rel_freq.csv')